### ISSUE TITLE
Menus not working

### ISSUE THREAD

**Issue by AgentFrameworks** [salcode/bootstrap-genesis#87] opened 2015-05-30 16:03 UTC
The menu dropdowns are not working with a fresh install of this theme. You click, nothing drops down.

**Comment by salcode** [comment] 2015-05-30 17:04
By default, Bootstrap menus only support dropdowns under top level items that don't have a real link (e.g. href="#"). For more elaborate navs adjustments need to be made or a third party plugin like Ubermenu.

Is this the problem you are seeing?

**Comment by AgentFrameworks** [comment] 2015-05-30 17:37
I don't think so.

http://kimberlygettle.agentmultisite.com/

I have # as the link for the parent link.

**Comment by salcode** [comment] 2015-05-30 18:20
Strange, the `<li>` should automatically (via JavaScript) get the class `.open` added when clicked.

You can see in the screenshot where I added it manually via Google Inspector.

However, it is not being added when clicked on your site.

![image](https://cloud.githubusercontent.com/assets/5194588/7898717/c1c3a0de-06d6-11e5-8859-59d3a34c3b80.png)

**Comment by salcode** [comment] 2015-05-30 18:23
Okay, it looks like somewhere `bootstrap.min.js` is being included in your theme, which should be removed.

Bootstrap Genesis includes Bootstrap's JavaScript in `javascript.min.js`.  My guess is when it gets included a second time, it is breaking the existing behavior.

Enqueuing that file would be the next thing I'd try.

If it still doesn't work, I'd disable all the plugins and try it again.

![image](https://cloud.githubusercontent.com/assets/5194588/7898724/0f55eb86-06d7-11e5-9c3d-060630705a90.png)

**Comment by AgentFrameworks** [comment] 2015-05-30 18:56
Thank you. I am sorry you had to do that. I should have known. I have a plugin that has bootstrap on it.  Thank you for your time.

**Comment by salcode** [comment] 2015-05-30 21:57
Nothing to apologize for @AgentFrameworks 

If we were enqueuing using a standard handle like "bootstrap" this problem might have been avoided but making that change leads to other problems (see #88)

I'm glad things are sorted.  I'm going to close this issue.

**Closed by salcode** 2015-05-30 21:57 UTC

**Comment by JacoVintage** [comment] 2015-08-11 10:33
I had a similar issue, it was caused by the plugin > "Bootstrap Shortcodes", which added "bootstrap.js". I removed the plugin for now. Thanks
